### ISSUE TITLE
transaction/s showing total 

### ISSUE THREAD

**Issue by lklemo** [liepumartins/netdata-sqlserver#1]
hello,
i have an issue with transaction/s showing total number of transaction in the chart not t/s.
it is continuously increasing number. 
is there any way to divide with time between 2 successful polls?
same with: latch waits 

also noticed that every time netdata is collecting counters are increased, is there any possibility to subtract that from being reported?

thank you

**Comment by liepumartins** [comment]
Hi,
Thank you for reporting this.

I believe that the issue is absolute vs incremental algorithm for certain charts.
I changed the algorithm for those charts where values, I believe, are meant to be per second.
Let me know if this is what you expected.

**Comment by lklemo** [comment]
Hi
yes now is reporting /second

thank you.
